-- CODE TO CHECK IF DATABASE IS EXIST OR NOT.
-- IT WILL DROP DATABASE AND YOU WILL LOSE ALL DATA.
DROP DATABASE IF EXISTS DataWarehouse;

-- CODE TO CREATE DATABASE.
CREATE DATABASE DataWarehouse;

USE DataWarehouse;

